---
- name: create route hello-world operator
  k8s:
    definition:
      kind: Service
      apiVersion: v1
      metadata:
        name: hello-world-nginx
        namespace: hello-world
        labels:
          app: hello-world-nginx
          app.kubernetes.io/component: hello-world-nginx
          app.kubernetes.io/instance: hello-world-nginx
          app.kubernetes.io/part-of: hello-world-nginx-app
          app.openshift.io/runtime-version: latest
      spec:
        ports:
          - name: 8080-tcp
            protocol: TCP
            port: 8080
            targetPort: 8080
        selector:
          app: hello-world-nginx
          deploymentconfig: hello-world-nginx
        clusterIP: 172.29.97.212
        type: ClusterIP
        sessionAffinity: None
